
storynator:
  ## Source is the section where you declare your input API.
  source:
      type: jira                                             # The type source of your application. Currently jira or trello

      file:
        location: /home/morlack/data/jira-examples

      jira:
          url: https://jira.codecentric.de/                         # URL to your JIRA environment
          project-key: GAR                                      # Your project key
          username: mitchell.herrijgers                                         # Basic auth key. Base64 encoded string of {username}:{password}
          password: Rmc8299512!

  report:
    dashboard:
      enabled: true
      url: http://localhost:8090/
      token: 58638583857aba00074cc02d